### ISSUE TITLE
adding keyboard events from the physical keyboard 

### ISSUE THREAD

**Issue by chavi362** [chavi362/virtual-keyboard#7]
I want that also if the user type in its regular keyboard in his computer the screen in the virtual keyboard will display what he types.
I want that also the user can see in the buttons of the virtual keyboard when he types a button in the regular. For example when he types 'a'  the button of 'a' in the virtual colored like it colored when it's hoverd.

**Comment by tiago1820** [comment]
This will be a big challenge for me.
I will do everything possible to resolve it.

**Comment by tiago1820** [comment]
Hello, @chavi362 .
I was without electricity for a few hours, due to a strong storm. 
I see that you already fixed the "unnecessary code" issue, thank you.
I wanted to explain that the physical keyboard recognition is working only for the languages: English, Portuguese and Spanish.
For the other languages, I am studying the case, but I already have an idea of what I have to do. I'm going to continue working on that.

Now I'm going to try to organize and clean the useEffect that recognizes the physical keyboard, because it is very big.

**Comment by tiago1820** [comment]
Hello, @chavi362 
Let me know when I can continue with work.

**Comment by chavi362** [comment]
Hi @tiago1820 how are you today?

**Comment by chavi362** [comment]
I made this changes.
I also built the function findCharIndex in languageData that returns the index of the char that user enterd in the keyboard so you can return the keyboardAaa[index] and if it -1 search for enter and etc.
Would you like to this?
If you don't want I can do it by myself, So please tell me

**Comment by tiago1820** [comment]
Hello @chavi362 ! Happy new year.

I would like to continue working on this topic. But I need a little time to learn how to use Redux Toolkit. I also want to use it in my projects.

So far I've only worked with React Redux.

If you're not in a hurry and can wait a bit, I can continue.

So as you want.
